### ISSUE TITLE
"embeds/./embeds/testEmbedding2-metadata.tsv" not found, or is not a file

### ISSUE THREAD

**Issue by StrangeTcy** [nlml/np-to-tf-embeddings-visualiser#2]
That's the error that Tensorboard is reporting after I run `tensorboard --logdir=embeds` as recommended. Meanwhile, a quick check shows that there're both `testEmbedding1-metadata.tsv` and `testEmbedding2-metadata.tsv` in `./embeds`

**Comment by StrangeTcy** [comment]
If I manually create an `./embeds/embeds` folder and copy all the files from the "outer" folder to the "inner" folder, everything works alright.
I suspect that the saving logic in `save_embeddings.py` is somewhat faulty.

**Comment by nlml** [comment]
Hmm okay, thanks for pointing that out.
